config/routes.rb
MyBlog::Application.routes.draw do

  resources :mailmes

  devise_for :users

  resources :posts do
    resources :comments
  end
  root :to => 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  attr_accessible :body, :commenter

  validates :body, :presence => true
  validates :commenter, :presence => true
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :description, :title
  has_many :comments

  validates :description, :presence => true
  validates :title, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
	def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(@post)
    @comment.save!
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	 def index
    @post = Post.find(params[:post_id])
  end
  def new
    @post = Post.find(params[:post_id])
  end
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment])
    redirect_to post_path(@post)
  end
end

app/controllers/mailmes_controller.rb
class MailmesController < ApplicationController
  # GET /mailmes
  # GET /mailmes.json
  def index
    @mailmes = Mailme.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mailmes }
    end
  end

  # GET /mailmes/1
  # GET /mailmes/1.json
  def show
    @mailme = Mailme.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mailme }
    end
  end

  # GET /mailmes/new
  # GET /mailmes/new.json
  def new
    @mailme = Mailme.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mailme }
    end
  end

  # GET /mailmes/1/edit
  def edit
    @mailme = Mailme.find(params[:id])
  end

  # POST /mailmes
  # POST /mailmes.json
  def create
    @mailme = Mailme.new(params[:mailme])

    respond_to do |format|
      if @mailme.save
        MeMailer.registration_confirm(@mailme).deliver!
        format.html { redirect_to @mailme, notice: 'Mailme was successfully created.' }
        format.json { render json: @mailme, status: :created, location: @mailme }
      else
        format.html { render action: "new" }
        format.json { render json: @mailme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mailmes/1
  # PUT /mailmes/1.json
  def update
    @mailme = Mailme.find(params[:id])

    respond_to do |format|
      if @mailme.update_attributes(params[:mailme])
        format.html { redirect_to @mailme, notice: 'Mailme was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mailme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mailmes/1
  # DELETE /mailmes/1.json
  def destroy
    @mailme = Mailme.find(params[:id])
    @mailme.destroy

    respond_to do |format|
      format.html { redirect_to mailmes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  	@posts = Post.page(params[:page]).per(3)
  end
  def new
  	@post = Post.new
  end
  def create
  	@post=Post.new(params[:post])
  	@post.save!
  	redirect_to @post
  end
  def show
  	@post = Post.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/index.html.erb
hello

app/views/comments/new.html.erb
<%= form_for [@post,@post.comments.build] do |p|%>
  <%= p.label :commenter %><br />
  <%= p.text_field :commenter %><br />

  <%= p.label :body %><br />
  <%= p.text_area :body%><br />

  <%= p.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyBlog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="user_nav">
    <% if user_signed_in? %>
     Logged In: <strong> <%= current_user.email %> </strong>.
     <%= link_to "Logout", destroy_user_session_path, :method => :delete %>
    <% else %>
      <%= link_to "SignUp", new_user_registration_path %>,
      <%= link_to "Login" , new_user_session_path %>
    <% end %>  
  </div>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/mailmes/_form.html.erb
<%= simple_form_for(@mailme) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :email %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/mailmes/edit.html.erb
<h1>Editing mailme</h1>

<%= render 'form' %>

<%= link_to 'Show', @mailme %> |
<%= link_to 'Back', mailmes_path %>

app/views/mailmes/index.html.erb
<h1>Listing mailmes</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @mailmes.each do |mailme| %>
  <tr>
    <td><%= mailme.name %></td>
    <td><%= mailme.email %></td>
    <td><%= link_to 'Show', mailme %></td>
    <td><%= link_to 'Edit', edit_mailme_path(mailme) %></td>
    <td><%= link_to 'Destroy', mailme, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Mailme', new_mailme_path %>

app/views/mailmes/new.html.erb
<h1>New mailme</h1>

<%= render 'form' %>

<%= link_to 'Back', mailmes_path %>

app/views/mailmes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @mailme.name %>
</p>

<p>
  <b>Email:</b>
  <%= @mailme.email %>
</p>


<%= link_to 'Edit', edit_mailme_path(@mailme) %> |
<%= link_to 'Back', mailmes_path %>

app/views/posts/index.html.erb
<% @posts.each do |p| %>
Post Title:<%= link_to p.title, post_path(p.id) %><br />
<% end %>
<%= paginate @posts %>
<%= link_to('Add Post', new_post_path)%> 

app/views/posts/new.html.erb
<%= simple_form_for @post do |p| %>
<%# p.label :title %><br />
<%# p.text_field :title %><br />
<%= p.input :title, :label => "Title" %>
<%# p.label :description %><br />
<%# p.text_area :description %><br />
<%= p.input :description, :input_html => { :class => "tinymce", :rows => "10", :cols => "50" } %>
<%= p.submit %>
<%= tinymce %>
<% end %>

app/views/posts/show.html.erb
Title: <%= @post.title %><br />
Description: <br /><%= raw @post.description %>

Comments:
<br />
<%= link_to 'Add Comment', new_post_comment_path(@post.id)%>
<br />
<br />
<% @post.comments.each do |p| %>
    Reviewer: &nbsp;
    <%= p.commenter%>
  <p>
    <%= p.body %>
  </p><br />
  <% end %>